// Code generated by "stringer -type=ReliabilityLevel"; DO NOT EDIT.

package base

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Super-0]
	_ = x[Reliable-1]
	_ = x[Common-2]
	_ = x[Occasional-3]
	_ = x[Erratic-4]
}

const _ReliabilityLevel_name = "SuperReliableCommonOccasionalErratic"

var _ReliabilityLevel_index = [...]uint8{0, 5, 13, 19, 29, 36}

func (i ReliabilityLevel) String() string {
	if i < 0 || i >= ReliabilityLevel(len(_ReliabilityLevel_index)-1) {
		return "ReliabilityLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReliabilityLevel_name[_ReliabilityLevel_index[i]:_ReliabilityLevel_index[i+1]]
}
